sudo: true
language: node_js
node_js:
  - "11"
cache: npm

install:
  - yarn 

before_script:
  - git config --global user.email "micalgenus@gmail.com"
  - git config --global user.name "GyeongSu Han"

script: 
  - yarn run test
  - CI=false yarn run build
  - SHA=$(git log | grep -E [a-z0-9]{40} | cut -d " " -f2 | cut -d$'\n' -f1 | cut -d " " -f1)
  - rm -rf $REPO
  - git clone https://$GITHUB_TOKEN@github.com/$USERNAME/$REPO.git
  - rm -rf $REPO/react && cp -R build $REPO/react
  - cd $REPO
  - git add --all react
  - COMMIT_MESSAGE='Updating to '$USERNAME'/'$REPO' from '$USERNAME'/portfolio@'$SHA
  - echo $COMMIT_MESSAGE
  - git commit -m $COMMIT_MESSAGE
  - git push https://$GITHUB_TOKEN@github.com/$USERNAME/$REPO.git --quiet

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'