sudo: true
language: node_js
node_js:
  - "11.10"
cache:
  npm: true
  yarn: true

branches:
  only:
    - develop

services:
  - docker

# before_install:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter

install:
  - yarn

# before_script:
#   - ./cc-test-reporter before-build

script:
  # - yarn run test
  # - yarn run test --coverage
  - yarn build

after_script:
  # - ./cc-test-reporter after-build --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push micalgenus/portfolio:develop && docker logout
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
