sudo: true
language: node_js
node_js:
  - '11.10'
cache:
  npm: true
  yarn: true
  # directories:
  #   - /home/google-cloud-sdk
  #   - /home/terraform

branches:
  only:
    - develop
    - travis

# services:
#   - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_eb0fbafef4ea_key -iv $encrypted_eb0fbafef4ea_iv -in keyfile.json.enc -out keyfile.json -d

  # Install Google Cloud SDK
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Install terraform
  - |
    if [ ! -d "$HOME/terraform/bin" ]; then
      rm -rf "$HOME/terraform"
      mkdir -p $HOME/terraform/bin
      wget https://releases.hashicorp.com/terraform/0.12.4/terraform_0.12.4_linux_amd64.zip
      unzip terraform_0.12.4_linux_amd64.zip -d $HOME/terraform/bin/
    fi
  - export PATH=$PATH:$HOME/terraform/bin

#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter

install:
  - yarn

before_script:
  - gcloud auth activate-service-account --key-file=keyfile.json
  - export TF_CREDS=keyfile.json
  - export TF_PROJECT=$(node gcloud.keyfile.js ./keyfile.json project_id)
  - export TF_VAR_project=$TF_PROJECT
  - export TRAVIS_WORKER_GCE_PROJECT_ID=$TF_PROJECT
  - export GCLOUD_ACCOUNT_EMAIL=$(node gcloud.keyfile.js ./keyfile.json client_email)
  - export GOOGLE_APPLICATION_CREDENTIALS=$TF_CREDS
#   - ./cc-test-reporter before-build

script:
  # - yarn run test
  # - yarn run test --coverage
  - yarn type-check
  - yarn build
  # - docker build -t $USERNAME/portfolio:develop .

deploy:
  # - provider: script
  #   script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push micalgenus/portfolio:develop && docker logout
  #   skip_cleanup: true
  #   on:
  #     branch: develop
  - provider: gae
    keyfile: ./keyfile.json
    project: micalgenus-com
    no_promote: true
    skip_cleanup: true
    on:
      branch: develop

after_deploy:
  - export APP_VERSION=$(gcloud app versions list --service=default --sort-by=~LAST_DEPLOYED --format="table(version.id)" --account=$GCLOUD_ACCOUNT_EMAIL | tail -1)
  - gcloud app services set-traffic default --splits $APP_VERSION=1 --migrate --account=$GCLOUD_ACCOUNT_EMAIL

# after_script:
#   - ./cc-test-reporter after-build --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
